### ISSUE TITLE
「ダウンロード」情報よりも「インストール情報」の方が有益ではないか

### ISSUE THREAD

**Issue by kou** [project-hatohol/website#15]
http://www.hatohol.org/ のページ上部のナビゲーションには「ダウンロード」リンクがありますが、ユーザーとしてはダウンロードしたいんじゃなくて使いたい気持ちの方が強いと思うので、インストール方法をわかりやすくした方がいいんじゃないかと思いました。

**Comment by Mnakagawa** [comment]
ダウンロードリンク削除済み。
インストールドキュメント，アップデートドキュメント共に作成されているため，
Issueの目的は完了したとみなしクローズします。
