### ISSUE TITLE
Webサイトのトップページにダウンロードボタンがあるがリンクが切れている

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/website#20]
![screenshot from 2014-12-04 18 57 02](https://cloud.githubusercontent.com/assets/700876/5296469/98d7b0f4-7be7-11e4-8c23-2309f1ad3445.png)

押すと404ページが出てきてしまう。

![screenshot from 2014-12-04 18 59 28](https://cloud.githubusercontent.com/assets/700876/5296478/b0cecfee-7be7-11e4-8a6c-dcfbf25f414c.png)

このボタンの扱いはどうあるべきなのでしょうか？

#### 案

* ボタン自体をなくす
* インストールドキュメントのリンクに変える。文言も「ダウンロード」から「インストール」に変更する。

**Comment by Mnakagawa** [comment]
削除済み
