### ISSUE TITLE
Hatohol 15.06のインストール手順書の問題点2つ

### ISSUE THREAD

**Issue by ytooyama** [project-hatohol/website#38]
ファイアウォールの設定とサービスの自動起動の設定について、変更前の手順書通りではアクセス不可の問題が発生するため、次の変更をしてPullしました。
https://github.com/project-hatohol/website/pull/37

firewall-cmdによるポート開放は--parmanentなしコマンド列を実行するか、 --parmanent付きコマンド列実行後に firewall-cmd --reload を実行しないとポートがあかないので修正。
2.修正前の手順ではhatoholとhttpdがシステム再起動後に起動しないので、各種サービスのOS起動時に自動起動するようにsystemctl enable列を追加。

**Comment by Mnakagawa** [comment]
マージ完了したためクローズします
